### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by DSGNS** [landonepps/op1.fun.app#2]
Hey thank you so much for updating this app!

I'm on Monterey 12.5.1
iMac 27" Late 2015

Uncaught Exception:
Error: dlopen(/Applications/op1fun.app/Contents/Resources/app/node_modules/drivelist/build/Release/drivelist.node, 0x0001): tried: '/Applications/op1fun.app/Contents/Resources/app/node_modules/drivelist/build/Release/drivelist.node' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at bindings (/Applications/op1fun.app/Contents/Resources/app/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/Applications/op1fun.app/Contents/Resources/app/node_modules/drivelist/js/index.js:25:27)

**Comment by landonepps** [comment]
Thanks for letting me know. To fix this we'll probably have to distribute separate builds for each platform.

**Comment by landonepps** [comment]
@DSGNS https://github.com/landonepps/op1.fun.app/releases/download/v2.0.0/op1fun-darwin-x64.zip
Try this x64 build I made.

**Comment by DSGNS** [comment]
@landonepps hell yeah man! works great! thank you so much

**Comment by landonepps** [comment]
This should be resolved on the master branch now
